DROP DATABASE IF EXISTS person_test;
CREATE DATABASE person_test DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE person_test;

DROP TABLE IF EXISTS person;

CREATE TABLE person (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);