plugins {
    id 'java'
    id 'application'
}

group = 'com.example'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.mysql:mysql-connector-j:9.3.0'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'com.h2database:h2:2.3.232'

    compileOnly 'org.projectlombok:lombok:1.18.38'
    annotationProcessor 'org.projectlombok:lombok:1.18.38'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
application {
    mainClass = 'com.example.jdbc.app.PersonTestMain'
}

test {
    useJUnitPlatform()
}